version: '3.8'

services:
  crawl4ai:
    image: ghcr.io/kevontym/crawl4ai:amd  # Explicit amd image for DigitalOcean Droplet
    ports:
      - "11235:11235"
    environment:
      API_TOKEN: "${API_TOKEN}"              # Add this in a .env file or hardcode
      CRON_EXPR: "*/15 * * * *"
      CRAWL4AI_DB_PATH: "/app/data"
      BROWSER_TYPE: "chromium"
      STORAGE_TYPE: "sqlite"
      DATABASE_URL: "sqlite:////app/data/articles.db"
    volumes:
      - ./crawl_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s